apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: anjiii22/food-delivery-system:latest  # Change if using another repo/tag
          imagePullPolicy: Always
          ports:
            - containerPort: 3004
          env:
            - name: PORT
              value: "3004"
            - name: MONGO_URI
              value: mongodb+srv://anjidipzimx:qwer%401234@mycluster.bgekn.mongodb.net/?retryWrites=true&w=majoritys
            - name: JWT_SECRET
              value: kasundi
            - name: JWT_EXPIRES_IN
              value: 1d
            # Add service discovery env if needed:
            # - name: RESTAURANT_API_URL
            #   value: http://restaurant-service:
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: NodePort
  selector:
    app: user
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 30004